USE [master]
GO

/****** Object:  Database [AddressEntry_old]    Script Date: 10/4/2014 3:17:14 PM ******/
CREATE DATABASE [AddressEntry_old]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AddressEntry', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\AddressEntry.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AddressEntry_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\AddressEntry_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AddressEntry_old] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AddressEntry_old].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AddressEntry_old] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AddressEntry_old] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AddressEntry_old] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AddressEntry_old] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AddressEntry_old] SET ARITHABORT OFF 
GO

ALTER DATABASE [AddressEntry_old] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AddressEntry_old] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AddressEntry_old] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AddressEntry_old] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AddressEntry_old] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AddressEntry_old] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AddressEntry_old] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AddressEntry_old] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AddressEntry_old] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AddressEntry_old] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AddressEntry_old] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AddressEntry_old] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AddressEntry_old] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AddressEntry_old] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AddressEntry_old] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AddressEntry_old] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AddressEntry_old] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AddressEntry_old] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AddressEntry_old] SET RECOVERY FULL 
GO

ALTER DATABASE [AddressEntry_old] SET  MULTI_USER 
GO

ALTER DATABASE [AddressEntry_old] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AddressEntry_old] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AddressEntry_old] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AddressEntry_old] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AddressEntry_old] SET  READ_WRITE 
GO

